In [1]:
import numpy as np
import time
import datetime
import multiprocessing as mp
from numpy.random import Generator, PCG64, SeedSequence
from lt_gen_sig_FNs_08ramSPAWNdxsmADD import gen_sig_tile, gen_sig_rns
np.set_printoptions(suppress=True)





In [2]:



start = time.perf_counter()






#nprocs = mp.cpu_count()-1
pool = mp.Pool(processes=3)

tile_count = 6

terms = 16
plays = 10**6

cutoff = (terms-1)/terms

final_results = []
endresults = []



for iterations in [2, 55]:
    for reinforce1 in range(2, 4, 1):
        reinforce2 = 0
        punish1 = 0
        for punish2 in range(-2, -6, -1):
#             punish1 = punish2

            sg = SeedSequence()
            rgs = [Generator(PCG64(s)) for s in sg.spawn(tile_count)]


            final_mp = pool.starmap(gen_sig_rns, [(n, terms, reinforce1, reinforce2, punish1, punish2, iterations, plays, rgs) for n in range(tile_count)])
            final_mp = np.asarray(final_mp)
            final_cumsuc = np.asarray(final_mp[:,0])
            final_measuc = np.asarray(final_mp[:,1])
            final_stepsuc = np.asarray(final_mp[:,2:5])
            # final_recweights= np.asarray(final_mp[:,2])

            # print('final_recweights')
            # print(final_recweights)

            print('time:')
            print(datetime.datetime.now())
            print(f'total runs = {tile_count}')
            # print(final_cumsuc)
            # print(final_measuc)

            mean_cumsuc = np.mean(final_cumsuc)
            runsuc_rate = final_measuc.copy()
            runsuc_rate[runsuc_rate >= cutoff] = 1
            runsuc_rate[runsuc_rate < cutoff] = 0
            final_rate = (np.sum(runsuc_rate))/tile_count
            
            meanstepsuc = np.mean(final_stepsuc, axis=0)

            print('run success rate')
            print(final_rate)
            
            print('mean step suc')
            print(meanstepsuc)

            params_results = [f'iterations = {iterations}', f'terms = {terms}', f'reinforce1 = {reinforce1}', f'reinforce2 = {reinforce2}', f'punish1 = {punish1} punish2 = {punish2}', f'mean cumulative success = {mean_cumsuc}', f'percent over (terms-1)/terms) = {final_rate}']
            print(params_results)

            final_results.append(params_results)
            endresults.append(final_rate)


print('***************************')
print('***************************')
print('FINAL RESULTS')
print('***************************')
print('***************************')
print(final_results)
print('***************************')
print('***************************')

print(endresults)

finish = time.perf_counter()
print(f'Finished in {round(finish-start,0)/60} minutes')

time:
2022-03-11 11:04:54.048510
total runs = 6
run success rate
0.3333333333333333
mean step suc
[0. 0. 0.]
['iterations = 2', 'terms = 16', 'reinforce1 = 2', 'reinforce2 = 0', 'punish1 = 0 punish2 = -2', 'mean cumulative success = 0.895341', 'percent over (terms-1)/terms) = 0.3333333333333333']
time:
2022-03-11 11:04:56.735430
total runs = 6
run success rate
0.6666666666666666
mean step suc
[0. 0. 0.]
['iterations = 2', 'terms = 16', 'reinforce1 = 2', 'reinforce2 = 0', 'punish1 = 0 punish2 = -3', 'mean cumulative success = 0.9438935', 'percent over (terms-1)/terms) = 0.6666666666666666']
time:
2022-03-11 11:04:59.532442
total runs = 6
run success rate
0.8333333333333334
mean step suc
[0. 0. 0.]
['iterations = 2', 'terms = 16', 'reinforce1 = 2', 'reinforce2 = 0', 'punish1 = 0 punish2 = -4', 'mean cumulative success = 0.907472', 'percent over (terms-1)/terms) = 0.8333333333333334']
time:
2022-03-11 11:05:02.317245
total runs = 6
run success rate
0.8333333333333334
mean step suc
[0. 0. 

KeyboardInterrupt: 